[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.145.0"

[[redirects]]
  from = "/wp-admin/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/wp-content/*"
  to = "/"
  status = 301
